executableModuleName=kbsx-frontoffice-application-openjfx
executableModuleVersion=1.0.0-SNAPSHOT
applicationModuleName=kbsx-frontoffice-application
pwa=null
mavenBuildTimestamp=${maven.build.timestamp}
environment=${webfx.meta.environment}